### ISSUE TITLE
is level-ttl suppose to work with chained batch?

### ISSUE THREAD

**Issue by kessler** [Level/level-ttl#38]
```
var levelup = require('levelup')
var levelTtl = require('level-ttl')

var db = levelTtl( levelup('db') )

var batch = db.batch()

batch.put(Date.now(), '2',  { valueEncoding: 'json', ttl: 12312 })

batch.write(function () {
	console.log(123)
})
```
results in:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
WriteError: batch() requires an array argument
    at writeError (/xxxxx/node_modules/levelup/lib/levelup.js:181:8)
    at LevelUP.batch (/xxxxx/node_modules/levelup/lib/levelup.js:304:12)
    at batch (/xxxxx/node_modules/level-ttl/level-ttl.js:275:17)
    at Object.<anonymous> (/xxxxx/index.js:6:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

removing level-ttl wrapper makes this code work.

Versions:
 "level-ttl": "^3.0.3",
 "leveldown": "^0.10.4",
 "levelup": "^0.19.0",

**Comment by ralphtheninja** [comment]
Nope it doesn't work since `level-ttl` overrides `batch()`. It should be possible to fix though. If no arguments are used it should return the chained batch from `levelup`.
